extract_usr_bin_time <- function(file) {
#' Extract information from a log file containig information obtained using "/usr/bin/time -v"
#'
#' This function extracts and processes a log file generated by the `/usr/bin/time -v` command
#' including user time, system time, CPU percentage, elapsed time (wall clock time),
#' and maximum resident set size. 
#'
#' @param file A character string specifying the path to the log file containing 
#'             the output of the `/usr/bin/time -v` command.
#'
#' @return A data frame containing the following columns:
#'   \describe{
#'     \item{UserTime_seconds}{The user CPU time in seconds.}
#'     \item{SystemTime_seconds}{The system CPU time in seconds.}
#'     \item{CPU_Percent}{The percentage of CPU utilized by the job.}
#'     \item{ElapsedTime_seconds}{The total elapsed (wall clock) time in seconds.}
#'     \item{ElapsedTime_hours}{The total elapsed time converted to hours (rounded to 2 decimals).}
#'     \item{MaxMemory_GB}{The maximum resident set size (memory usage) in gigabytes (rounded to 2 decimals).}
#'   }
#'
#' @details
#' The function searches the provided log file for the following fields:
#' - User time (in seconds)
#' - System time (in seconds)
#' - CPU percentage
#' - Elapsed time (in "h:mm:ss" or "m:ss" format)
#' - Maximum resident set size (in kilobytes)
#'
#' The extracted values are processed and converted into seconds, hours, and gigabytes where applicable.
#' The elapsed time is converted to total seconds. 
#'
#' @examples
#' \dontrun{
#' # Assuming 'usr_time_log.txt' is the log file containg the output generated by "/usr/bin/time -v"
#' result <- process_usr_bin_time("usr_time_log.txt")
#' print(result)
#' }
#'
#' @importFrom stringr str_extract str_subset
#' @export
#' 
############# END DOCUMENTATION ############################################
    library(stringr)
    if(file.exists(file)) {
        lines <- readLines(file)
    } else {
        cat("\n File ", file, "does not exists.")
    }
    # Function to parse elapsed time
    parse_time <- function(time_str) {
        # Split the time string into components using ":" as a separator
        time_parts <- unlist(strsplit(time_str, ":"))
        
        if (length(time_parts) == 3) {
            # Convert h:mm:ss format to total seconds
            return(as.numeric(time_parts[1]) * 3600 + as.numeric(time_parts[2]) * 60 + as.numeric(time_parts[3]))
        } else if (length(time_parts) == 2) {
            # Convert m:ss format to total seconds
            return(as.numeric(time_parts[1]) * 60 + as.numeric(time_parts[2]))
        } else {
            # Return NA if the format is not recognized
            return(NA)
        }
    }

    # User time
    user_time <- str_subset(lines, "User time \\(seconds\\): ([0-9.]+)")
    user_time_numeric <- as.numeric(str_extract(user_time, "[0-9.]+"))

    # System time
    system_time <- str_subset(lines, "System time \\(seconds\\): ([0-9.]+)")
    system_time_numeric <- as.numeric(str_extract(system_time, "[0-9.]+"))

    # CPU percentage
    cpu_percent <- str_subset(lines, "Percent of CPU this job got: ([0-9.]+)%")
    cpu_percent_numeric <- as.numeric(str_extract(cpu_percent, "[0-9.]+"))

    # Elapsed time
    elapsed_time <- str_subset(lines, "Elapsed \\(wall clock\\) time \\(h:mm:ss or m:ss\\): ([0-9:]+)")
    elapsed_time_parsed <- parse_time(str_extract(elapsed_time, "(?<=Elapsed \\(wall clock\\) time \\(h:mm:ss or m:ss\\): )([0-9]+:[0-9]+(:[0-9]+)?)"))

    # Maximum resident size
    max_resident_size <- str_subset(lines, "Maximum resident set size \\(kbytes\\): ([0-9]+)")
    max_resident_size_numeric <- as.numeric(str_extract(max_resident_size, "[0-9]+"))

    # Convert data to human-readable format
    elapsed_time_hr <- elapsed_time_parsed / 3600  # Convert elapsed time to hours
    max_resident_size_gb <- max_resident_size_numeric / 1024^2  # Convert memory usage to gigabytes

    # Create a data frame to store the information
    values <- data.frame(
      UserTime_seconds = user_time_numeric,           # User CPU time in seconds
      SystemTime_seconds = system_time_numeric,       # System CPU time in seconds
      CPU_Percent = cpu_percent_numeric,              # Percentage of CPU utilized
      ElapsedTime_seconds = elapsed_time_parsed,      # Total elapsed time in seconds
      ElapsedTime_hours = round(elapsed_time_hr, 2),  # Elapsed time in hours (rounded to 2 decimal places)
      MaxMemory_GB = round(max_resident_size_gb, 2)   # Maximum memory usage in GB (rounded to 2 decimal places)
    )
    return(values)
}